pipeline {
 agent any

 stages {

 stage('Clone') {
 steps {
 git 'https://github.com/psakthiece/Trendstore/tree/main/Trend'
 }
 }

 stage('Build Image') {
 steps {
 sh 'docker build -t trend-app .'
 }
 }

 stage('Push Image') {
 steps {
 sh 'docker push yourdockerhubusername/trend-app:latest'
 }
 }

 stage('Deploy to Kubernetes') {
 steps {
 sh 'kubectl apply -f k8s/'
 }
 }

 }
}
